#!/bin/bash

date '+%b %d %Y (%a) %I:%M%p'

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send "$(cal -H yyyy-mm-dd)" ;;
# "$(cal --color=always | sed "s/..7m/<b><span>colur=\"magenta\">/;s/..27m/<\/span><\/b>/")" ;;
	2) urxvt -e calcurse ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b>📅 Time/date module:</b>
- Left click to show month via \`cal\`
- Middle click opens calcurse if installed" ;;
esac

